### ISSUE TITLE
Move this repository to a TRAPSat organization

### ISSUE THREAD

**Issue by EzraBrooks** [sandyfreelance/TRAPSat#4]
To facilitate using this code for future launches, we should make a TRAPSat organization and transfer ownership of this repository to it. @krmoore will have to do this, since he owns the repository.

**Comment by EzraBrooks** [comment]
Update: there is a TRAPSat repository at https://github.com/CACTUS-Mission/TRAPSat. @sandyfreelance, I can give you administrative access to the CACTUS GitHub group if you'd like.

**Comment by sandyfreelance** [comment]
Hi Ezra,

Yes, please do give me admin access (email is 'sandy@rpg.net' for github).

Thanks!
Antunes

**Comment by EzraBrooks** [comment]
Done. The repository on the CACTUS organization page has the entire commit history from this one, so it might be worth getting rid of this one (and if you want to keep your own copy of TRAPSat, you can fork the one from CACTUS) so there's less confusion as to where the code is.
